version: "3.9"

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    image: nginx
    restart: always
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - .env
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb
    restart: always
    networks:
      - inception
    ports:
      - 3306:3306
    volumes:
      - mariadb:/var/lib/mysql
    env_file:
      - .env
    

networks:
  inception:
    driver: bridge

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/${USER}/data/mariadb